# These are supported funding model platforms
# Uncomment github line after setting up GitHub Sponsors at https://github.com/sponsors

# github: jean-voila
custom: ["bitcoin:bc1qa0xyd9n0fy0hhk2mzg5g5zy8l7lc0t728f0jnq"]
